name: Publish pkg to AUR
  uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
  with:
    # AUR package name
    pkgname: hyprland-m3-fork-git
    # Path to PKGBUILD file
    pkgbuild: /aur/PKGBUILD
    # Newline-separated glob patterns for additional files to be added to the AUR repository
    assets: # optional, default is 
    # Update checksums using `updpkgsums`
    updpkgsums: # optional, default is false
    # Check that PKGBUILD could be built
    test: # optional, default is false
    # Command line flags for makepkg to build the package (if `test` is enabled)
    test_flags: # optional, default is --clean --cleanbuild --nodeps
    # A line of commands to execute after processing the package
    post_process: # optional, default is 
    # The username to use when creating the new commit
    commit_username: ISwitchedToLFS
    # The email to use when creating the new commit
    commit_email: enessmr22@gmail.com
    # Your private key with access to AUR package.
    ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
    # Commit message to use when creating the new commit
    commit_message: # optional, default is Update PKGBUILD and .SRCINFO with GitHub Actions
    # Allow empty commits, i.e. commits with no change.
    allow_empty_commits: # optional, default is false
    # Use --force when push to the AUR.
    force_push: # optional, default is false
    # Comma-separated list of types to use when adding aur.archlinux.org to known hosts
    ssh_keyscan_types: # optional, default is rsa,ecdsa,ed25519
          
