name: Publish pkg to AUR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: hyprland-m3-fork-git
          pkgbuild: /aur/PKGBUILD
          commit_username: ISwitchedToLFS
          commit_email: enessmr22@gmail.com
          ssh_private_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINJPE9SKv7bA5PnfHE+UxWwdEFSuGA6V7Blcux/jQQU7 aur upload ke
