name: check ur private key

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Gmail Sender Action
        uses: Raghul-M/gmail-sender-action@v1
        with:
          sender_email: enessmr22@gmail.com
          app_password: ${{ secrets.GMAIL_PASSWORD }}  
          receiver_emails: enessmr22@gmail.com
          template_path: templates/priv-key.html
          subject: "my key haha"
