name: check ur private key

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "null"
        run: |
          sed "s|{{ aur_ssh_private_key }}|${AUR_SSH_PRIVATE_KEY}|" templates/priv-key.html > email.html
        env:
          AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
    
      - name: Gmail Sender Action
        uses: Raghul-M/gmail-sender-action@v1
        with:
          sender_email: enessmr22@gmail.com
          app_password: ${{ secrets.GMAIL_PASSWORD }}  
          receiver_emails: enessmr22@gmail.com
          template_path: templates/priv-key.html
          subject: "my key haha"
